version: 5.0.{build}
skip_tags: true
image: Visual Studio 2019

before_build:
- git checkout issue-278
- ps: .\prep_build.ps1 "$env:APPVEYOR_BUILD_VERSION" "$env:IS_RELEASE"
- type ".\ProTONE Suite\src\Framework\OPMediaBase\OPMedia.Core\Version.cs"

build_script:
- dotnet build ".\ProTONE Suite\src\ProTONE Suite.sln"
  
after_build:
- copy ".\ProTONE Suite\src\Installers\Romanian.isl" "C:\Program Files (x86)\Inno Setup 6\Languages"
- set PATH=%PATH%;"C:\Program Files (x86)\Inno Setup 6"
- ISCC /Q ".\ProTONE Suite\src\Installers\ProtoneSuite.iss"
- copy .\*.txt ".\ProTONE Suite\output"
- 7z a protone-setup.zip ".\ProTONE Suite\output\*.*"

artifacts:
- path: protone-setup.zip
  name: protone-setup

deploy:
    provider: FTP
    protocol: ftp
    host: ocpa.ro
    username: ocparo_ftpops
    password: 
        secure: Vu0FvCIJ5sKkVuiZoWBhUA==
    folder: content/ProTONE/current/
    application: protone-setup
