version: 3.1.{build}
skip_tags: true
image: Visual Studio 2017

before_build:
- nuget restore ".\ProTONE Suite\src\ProTONE Suite.sln"

build:
  project: .\ProTONE Suite\src\ProTONE Suite.sln
  verbosity: minimal
  
after_build:
- set PATH=%PATH%;"C:\Program Files (x86)\Inno Setup 5"
- ISCC /Q  ".\ProTONE Suite\src\Installers\ProtoneSuite.iss"

