version: 3.1.{build}
skip_tags: true
image: Visual Studio 2017

environment:
  access_token:
    secure: AdNddFLS8qRKDQ0iJayURTbXSMKvCJ7nXbME8W/wmCL9xF2MAGMC89a1NqZ03Hpg
  ftp_host: 
    secure: ALADPEGH8w9Rf9Y68/VfGg==
  ftp_user: 
    secure: Y6/oR8gHd/tadZ97TJLkTg==
  ftp_pass:
    secure: WLrEKSe6D0A7YU3E96co+w==
  ftp_folder: 
    secure: amy8jP385jc3l1gSkkG2cQCcTSRWo4IQdFF2BrUu6T4=
    

before_build:
- git checkout master
- rem "Initializing build version ..."
- ps: .\prep_build.ps1 "$env:APPVEYOR_BUILD_VERSION" "$env:IS_RELEASE"
- type ".\ProTONE Suite\src\Framework\OPMediaBase\OPMedia.Core\Version.cs"

- rem "Restoring NuGet packages from ProTONE Suite solution ..."
- nuget restore ".\ProTONE Suite\src\ProTONE Suite.sln" -Verbosity Quiet

build_script:
- rem "Building ProTONE Suite solution ..."
- msbuild /restore /p:Configuration=Debug /t:Rebuild ".\ProTONE Suite\src\ProTONE Suite.sln" /v:minimal 
  
after_build:
- rem "Copying Romanian language file for Inno Setup"
- copy ".\ProTONE Suite\src\Installers\Romanian.isl" "C:\Program Files (x86)\Inno Setup 5\Languages"

- rem "Building ProTONE Suite installer ..."
- set PATH=%PATH%;"C:\Program Files (x86)\Inno Setup 5"
- ISCC /Q ".\ProTONE Suite\src\Installers\ProtoneSuite.iss"

- rem "Generating artifacts ..."
- copy .\*.txt ".\ProTONE Suite\output"
- dir ".\ProTONE Suite\output"
- 7z a protone-setup.zip ".\ProTONE Suite\output\*.*"

artifacts:
- path: protone-setup.zip
  name: protone-setup

deploy:
    provider: FTP
    protocol: ftp
    host: $env:ftp_host
    username: $env:ftp_user
    password: $env:ftp_pass
    folder: $env:ftp_folder
    application: protone-setup
  
on_success:
    - dir
    - git config --global credential.helper store
    - ps: Add-Content "$env:USERPROFILE\.git-credentials" "https://$($env:access_token):x-oauth-basic@github.com`n"
    - git config --global user.email "octavian.paraschiv@gmail.com"
    - git config --global user.name "octavian-paraschiv"
    - git commit -a -m "build_%APPVEYOR_BUILD_VERSION% (release:%IS_RELEASE%)"
    - git push --all --progress origin
