version: 3.1.{build}
skip_tags: true
image: Visual Studio 2017

before-build:
- nuget restore .\ProTONE Suite\src\ProTONE Suite.sln

build:
  project: .\ProTONE Suite\src\ProTONE Suite.sln
  verbosity: minimal