//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OPMedia.RCCManager.Translations {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Translation {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Translation() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OPMedia.RCCManager.Translations.Translation", typeof(Translation).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new button ....
        /// </summary>
        internal static string TXT_ADD_BUTTON {
            get {
                return ResourceManager.GetString("TXT_ADD_BUTTON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new remote control ....
        /// </summary>
        internal static string TXT_ADD_DEVICE {
            get {
                return ResourceManager.GetString("TXT_ADD_DEVICE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add button.
        /// </summary>
        internal static string TXT_ADD_ONCE {
            get {
                return ResourceManager.GetString("TXT_ADD_ONCE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add button, and repeat.
        /// </summary>
        internal static string TXT_ADD_REPEAT {
            get {
                return ResourceManager.GetString("TXT_ADD_REPEAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Button on &apos;{0}&apos;.
        /// </summary>
        internal static string TXT_ADDBUTTON {
            get {
                return ResourceManager.GetString("TXT_ADDBUTTON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Remote Control.
        /// </summary>
        internal static string TXT_ADDREMOTECONFIG {
            get {
                return ResourceManager.GetString("TXT_ADDREMOTECONFIG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Remote Control Manager requires administrator rights to run.
        ///You must launch this application under a user account that has administrator rights..
        /// </summary>
        internal static string TXT_ADMIN_RIGHTS_REQUIRED {
            get {
                return ResourceManager.GetString("TXT_ADMIN_RIGHTS_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remote Control Manager.
        /// </summary>
        internal static string TXT_APP_NAME {
            get {
                return ResourceManager.GetString("TXT_APP_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save configuration ?.
        /// </summary>
        internal static string TXT_APPLY_CFG {
            get {
                return ResourceManager.GetString("TXT_APPLY_CFG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save remote control configuration.
        /// </summary>
        internal static string TXT_APPLYTIP {
            get {
                return ResourceManager.GetString("TXT_APPLYTIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string TXT_BUTTON_NAME {
            get {
                return ResourceManager.GetString("TXT_BUTTON_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Button name:.
        /// </summary>
        internal static string TXT_BUTTONNAME {
            get {
                return ResourceManager.GetString("TXT_BUTTONNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Button name: {0} [ &apos;{1}&apos; --&gt; &apos;{2}&apos; ].
        /// </summary>
        internal static string TXT_BUTTONNAME_FULL {
            get {
                return ResourceManager.GetString("TXT_BUTTONNAME_FULL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remote control buttons.
        /// </summary>
        internal static string TXT_BUTTONS {
            get {
                return ResourceManager.GetString("TXT_BUTTONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This pin can be configured only from ProTONE Player..
        /// </summary>
        internal static string TXT_CFG {
            get {
                return ResourceManager.GetString("TXT_CFG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pin settings:.
        /// </summary>
        internal static string TXT_CFGDATA {
            get {
                return ResourceManager.GetString("TXT_CFGDATA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure Button on &apos;{0}&apos;.
        /// </summary>
        internal static string TXT_CHANGEBUTTON {
            get {
                return ResourceManager.GetString("TXT_CHANGEBUTTON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure Remote Control.
        /// </summary>
        internal static string TXT_CHANGEEMOTECONFIG {
            get {
                return ResourceManager.GetString("TXT_CHANGEEMOTECONFIG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remote Control Configuration files (*.config)|*.config||.
        /// </summary>
        internal static string TXT_CONFIG_FILES_FILTER {
            get {
                return ResourceManager.GetString("TXT_CONFIG_FILES_FILTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to remove the selected remote control button?
        ///You will not be able to undo this removal !.
        /// </summary>
        internal static string TXT_CONFIRMDELETEBUTTON {
            get {
                return ResourceManager.GetString("TXT_CONFIRMDELETEBUTTON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to remove the selected remote control ?
        ///You will not be able to undo this removal !.
        /// </summary>
        internal static string TXT_CONFIRMDELETEREMOTE {
            get {
                return ResourceManager.GetString("TXT_CONFIRMDELETEREMOTE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default_window_name.
        /// </summary>
        internal static string TXT_DEFAULTWINDOWNAME {
            get {
                return ResourceManager.GetString("TXT_DEFAULTWINDOWNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete existing button.
        /// </summary>
        internal static string TXT_DEL_BUTTON {
            get {
                return ResourceManager.GetString("TXT_DEL_BUTTON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete existing remote control.
        /// </summary>
        internal static string TXT_DEL_DEVICE {
            get {
                return ResourceManager.GetString("TXT_DEL_DEVICE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detect.
        /// </summary>
        internal static string TXT_DETECT {
            get {
                return ResourceManager.GetString("TXT_DETECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remote control name: {0}.
        /// </summary>
        internal static string TXT_DEVICENAME {
            get {
                return ResourceManager.GetString("TXT_DEVICENAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pin settings not defined yet..
        /// </summary>
        internal static string TXT_ENTERDATA {
            get {
                return ResourceManager.GetString("TXT_ENTERDATA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input data (press Detect to receive data):.
        /// </summary>
        internal static string TXT_INPUTDATA {
            get {
                return ResourceManager.GetString("TXT_INPUTDATA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input pin: {0} {1}.
        /// </summary>
        internal static string TXT_INPUTPIN {
            get {
                return ResourceManager.GetString("TXT_INPUTPIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input pin settings.
        /// </summary>
        internal static string TXT_INPUTPINDATA {
            get {
                return ResourceManager.GetString("TXT_INPUTPINDATA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modify existing button ....
        /// </summary>
        internal static string TXT_MOD_BUTTON {
            get {
                return ResourceManager.GetString("TXT_MOD_BUTTON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modify existing remote control ....
        /// </summary>
        internal static string TXT_MOD_DEVICE {
            get {
                return ResourceManager.GetString("TXT_MOD_DEVICE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buttons are not yet defined for this remote control..
        /// </summary>
        internal static string TXT_NO_BUTTONS_YET {
            get {
                return ResourceManager.GetString("TXT_NO_BUTTONS_YET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This remote control doesn&apos;t need button configuration..
        /// </summary>
        internal static string TXT_NOBUTTONSREQUIRED {
            get {
                return ResourceManager.GetString("TXT_NOBUTTONSREQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pin settings not defined yet..
        /// </summary>
        internal static string TXT_NODATA {
            get {
                return ResourceManager.GetString("TXT_NODATA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This pin doesn&apos;t need any settings..
        /// </summary>
        internal static string TXT_NOTCFG {
            get {
                return ResourceManager.GetString("TXT_NOTCFG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data to output pin:.
        /// </summary>
        internal static string TXT_OUTPUTDATA {
            get {
                return ResourceManager.GetString("TXT_OUTPUTDATA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output pin: {0} {1}.
        /// </summary>
        internal static string TXT_OUTPUTPIN {
            get {
                return ResourceManager.GetString("TXT_OUTPUTPIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output pin settings.
        /// </summary>
        internal static string TXT_OUTPUTPINDATA {
            get {
                return ResourceManager.GetString("TXT_OUTPUTPINDATA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pin type:.
        /// </summary>
        internal static string TXT_PINTYPE {
            get {
                return ResourceManager.GetString("TXT_PINTYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press the key combination you want to assign..
        /// </summary>
        internal static string TXT_PRESS_KEY {
            get {
                return ResourceManager.GetString("TXT_PRESS_KEY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press a button on the remote control.
        ///To skip detection, press Enter or Escape..
        /// </summary>
        internal static string TXT_PRESSBUTTON {
            get {
                return ResourceManager.GetString("TXT_PRESSBUTTON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ProTONE Remote Control Command:.
        /// </summary>
        internal static string TXT_PROTONE_REMOTE_COMMAND {
            get {
                return ResourceManager.GetString("TXT_PROTONE_REMOTE_COMMAND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remote control list:.
        /// </summary>
        internal static string TXT_REMOTELIST {
            get {
                return ResourceManager.GetString("TXT_REMOTELIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remote control name:.
        /// </summary>
        internal static string TXT_REMOTENAME {
            get {
                return ResourceManager.GetString("TXT_REMOTENAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have made changes to the configuration.
        ///Do you want to save these changes before exiting ?.
        /// </summary>
        internal static string TXT_SAVE_BEFORE_EXIT {
            get {
                return ResourceManager.GetString("TXT_SAVE_BEFORE_EXIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to seconds..
        /// </summary>
        internal static string TXT_SECONDS {
            get {
                return ResourceManager.GetString("TXT_SECONDS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target window.
        /// </summary>
        internal static string TXT_TARGET_WNDNAME {
            get {
                return ResourceManager.GetString("TXT_TARGET_WNDNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title of target application/window:.
        /// </summary>
        internal static string TXT_TARGETWNDNAME {
            get {
                return ResourceManager.GetString("TXT_TARGETWNDNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command repetition interval: 
        ///(0 = no repetition).
        /// </summary>
        internal static string TXT_TIMEDREPEATRATE {
            get {
                return ResourceManager.GetString("TXT_TIMEDREPEATRATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send commands to the active program window.
        /// </summary>
        internal static string TXT_WINDOWBASED {
            get {
                return ResourceManager.GetString("TXT_WINDOWBASED", resourceCulture);
            }
        }
    }
}
